from __future__ import annotations

from typing import Any, Generic, TypeVar

_T = TypeVar("_T")

class DeclarativeBase: ...
class Mapped(Generic[_T]): ...

def mapped_column(*args: Any, **kwargs: Any) -> Mapped[Any]: ...
def relationship(*args: Any, **kwargs: Any) -> Any: ...
