from __future__ import annotations

from typing import Any, Sequence

class DateTime: ...
class JSON: ...

class MetaData:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Text: ...

class String:
    def __init__(self, length: int | None = ...) -> None: ...

class Integer: ...
class Boolean: ...
class Float: ...

class Enum:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ForeignKey:
    def __init__(self, target: str, *, ondelete: str | None = ...) -> None: ...

class Index:
    def __init__(
        self, name: str, *columns: Any, unique: bool | None = ..., **kwargs: Any
    ) -> None: ...

class JSONB: ...
class Uuid: ...

def text(value: str) -> Any: ...

class func:
    @staticmethod
    def now() -> Any: ...

__all__: Sequence[str]
