from __future__ import annotations

from typing import Any, Awaitable, Callable, Generic, Protocol, TypeVar

class AsyncEngine:
    async def dispose(self) -> None: ...

class AsyncSession: ...

_T = TypeVar("_T")

class async_sessionmaker(Generic[_T]):
    def __call__(self, *args: Any, **kwargs: Any) -> _T: ...

def create_async_engine(url: str, *args: Any, **kwargs: Any) -> AsyncEngine: ...
def async_sessionmaker(*args: Any, **kwargs: Any) -> async_sessionmaker[AsyncSession]: ...
def async_engine_from_config(*args: Any, **kwargs: Any) -> AsyncEngine: ...
