from collections.abc import Iterator, MutableMapping
from typing import Generic, TypeVar

KT = TypeVar("KT")
VT = TypeVar("VT")

class TTLCache(MutableMapping[KT, VT], Generic[KT, VT]):
    maxsize: int
    ttl: float

    def __init__(self, maxsize: int, ttl: float) -> None: ...
    def __getitem__(self, __key: KT) -> VT: ...
    def __setitem__(self, __key: KT, __value: VT) -> None: ...
    def __delitem__(self, __key: KT) -> None: ...
    def __iter__(self) -> Iterator[KT]: ...
    def __len__(self) -> int: ...
